descriptor-schema-version: "2.2"

info:
  name: iox-node-red
  description: "A Node-Red server for iOX"
  version: "1.0"
  author-link: "https://github.com/cappern/iox-node-red"
  author-name: "Cappern"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  cpuarch: "x86_64"
  type: docker
  resources:
    profile: c1.medium
    platform-env:
         - NODE_PATH=/usr/src/node-red/node_modules:/data/appdata/node_modules

    network:
      -
        interface-name: eth0
        ports:
            tcp: [1880]

# Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["npm", "start" ,"--prefix", "usr/src/node-red/", "--", "--userDir", "/data/appdata", "--settings", "/usr/src/node-red/settings.js"]